# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: app.js CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'api/src/**'
      - 'api/test/**/*.spec.ts'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'api/src/**/*.ts'
      - 'api/test/**/*.spec.ts'


jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    strategy:
      matrix:
        node-version: [20.x, 22.x]
        #node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './api/package-lock.json' # Adjust path as needed
    - run: npm install --force
    - run: npm run build --if-present 
    - run: npm run test
